AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  proper example that uses "Physical Resource ID" to let CloudFormation handle deletes for you, if you change the BucketName input parameter

Globals:
  Function:
    Timeout: 10

Parameters:
  BucketName:
    Type: String

Resources:
  CustomS3Bucket:
    Type: Custom::S3Bucket
    Properties:
      ServiceToken: !GetAtt CustomS3BucketHandler.Arn
      BucketName: !Ref BucketName

  CustomS3BucketHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/
      Handler: main.handler
      Runtime: python3.8
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "s3:*"
              Resource: "*"
