AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  same implementation as `s3bucket`, but will generate a bucket name itself, if not provided explicitly.

Globals:
  Function:
    Timeout: 10

Parameters:
  BucketName:
    Type: String
    Default: ""

Resources:
  CustomS3BucketRandomName:
    Type: Custom::S3BucketRandomName
    Properties:
      ServiceToken: !GetAtt CustomS3BucketRandomNameHandler.Arn
      BucketName: !Ref BucketName

  CustomS3BucketRandomNameHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/
      Handler: main.handler
      Runtime: python3.8
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "s3:*"
              Resource: "*"
